font_family Fira Code
# font_family Source Code Pro
# font_family JetBrainsMono NF
# font_family Ubuntu Nerd Font Mono

italic_font      auto
bold_italic_font auto
font_size 16.0

background #101010

# window_padding_width 10 10 0
# window_margin_width 10 10 0
window_margin_width 15 15 0
hide_window_decorations yes

map ctrl+alt+enter launch --cwd=current --type=os-window

# enable_audio_bell no

# cursor #990099
cursor_shape block
shell_integration  no-cursor

map ctrl+shift+equal change_font_size current +2.0
map ctrl+shift+minus change_font_size current -2.0
map ctrl+shift+backspace change_font_size current 0
